[versions]
windowlicker = "r268"
smack = "4.5.0-beta8"

[libraries]
windowlicker = { module = "com.googlecode.windowlicker:windowlicker-swing", version.ref = "windowlicker" }
smack = { module = "org.igniterealtime.smack:smack-java11", version.ref = "smack" }
smack-tcp = { module = "org.igniterealtime.smack:smack-tcp", version.ref = "smack" }
smack-im = { module = "org.igniterealtime.smack:smack-im", version.ref = "smack" }
smack-extensions = { module = "org.igniterealtime.smack:smack-extensions", version.ref = "smack" }
